/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe_management;

import javax.swing.JOptionPane;
import model.User;
import Dao.userQu;
import java.lang.Integer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * 
 * @author User
 */
public class Signup extends javax.swing.JFrame {

   public String emailpattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
   public String phone_num_pattern="^[0-9]*$";
   public String name_pattern="^[a-zA-Z]+$";
    private User query;
   
   
   
    public Signup() {
        initComponents();
        bt_save.setEnabled(false);
    }
    
    public void clear()
    {
        txt_name.setText("");
        txt_address.setText("");
        txt_DOB.setText("");
        txt_number.setText("");
        txt_mail.setText("");
        txt_password.setText("");
        bt_save.setEnabled(false);
    }
    
    public void validateField()
    {
        String name=txt_name.getText();
        String Address=txt_address.getText();
        String DOB=txt_DOB.getText();
        String Phone_number=txt_number.getText();
        String email=txt_mail.getText();
        String password=txt_password.getText();
       
        try
        {
        if(!name.equals("")||!name.isEmpty()||!name.matches("^[a-zA-Z ]+$")||!!phone_number.matches("^\\d{10}$")||!address.isEmpty()|| !name.equals(ABORT) || name.matches(name_pattern) ||email.matches(emailpattern)||Phone_number.matches(phone_num_pattern)||Phone_number.length()==10||!Address.equals("")|| password.length() < 6||!password.equals(""))
           {
               bt_save.setEnabled(true);
                           
           }
        
        else
        {
            bt_save.setEnabled(false);
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, bt_save);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_DOB = new javax.swing.JTextField();
        txt_number = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        bt_clear = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();
        bt_save = new javax.swing.JButton();
        bt_forgetpassword = new javax.swing.JButton();
        bt_login = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Signup");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 145, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 231, 151, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 273, 151, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 321, 151, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 365, 151, -1));

        txt_DOB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_DOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DOBKeyReleased(evt);
            }
        });
        getContentPane().add(txt_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 318, 330, -1));

        txt_number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numberKeyReleased(evt);
            }
        });
        getContentPane().add(txt_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 362, 330, -1));

        txt_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 228, 330, -1));

        txt_mail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_mailKeyReleased(evt);
            }
        });
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 399, 330, -1));

        txt_address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_addressKeyReleased(evt);
            }
        });
        getContentPane().add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 270, 330, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 406, 151, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 448, 151, -1));

        txt_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 445, 330, -1));

        bt_clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        bt_clear.setText("Clear");
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });
        getContentPane().add(bt_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 501, -1, -1));

        bt_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        bt_exit.setText("Exit");
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });
        getContentPane().add(bt_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 501, -1, -1));

        bt_save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });
        getContentPane().add(bt_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 501, -1, -1));

        bt_forgetpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_forgetpassword.setText("Forget Password ?");
        bt_forgetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_forgetpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(bt_forgetpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, -1, -1));

        bt_login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        bt_login.setText("Login");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1016894.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, -1, 1020));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 80, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
           
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to Close Application","Selection",JOptionPane.YES_NO_OPTION);
        
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_bt_exitActionPerformed

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        // TODO add your handling code here:
        User user=new User();
        user.setName(txt_name.getText());
        user.setAddress(txt_address.getText());
        user.setDOB(txt_DOB.getText());
        user.setPhone_num(txt_number.getText());
        user.setEmail(txt_mail.getText());
        user.setPassword(txt_password.getText());
        validateField();
        userQu.save(user);
        
        clear();
        
    }//GEN-LAST:event_bt_saveActionPerformed

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        // TODO add your handling code here:
        clear();
        
    }//GEN-LAST:event_bt_clearActionPerformed

    private void txt_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txt_nameKeyReleased

    private void txt_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_addressKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txt_addressKeyReleased

    private void txt_DOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DOBKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txt_DOBKeyReleased

    private void txt_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numberKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txt_numberKeyReleased

    private void txt_mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mailKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txt_mailKeyReleased

    private void txt_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyTyped
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txt_nameKeyTyped

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_forgetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_forgetpasswordActionPerformed
        // TODO add your handling code here:
        
        
        new ForgetPassword().setVisible(true);
    }//GEN-LAST:event_bt_forgetpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_forgetpassword;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_DOB;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_number;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
